### ISSUE TITLE
python setup.py install not working

### ISSUE THREAD

**Issue by calebjones422** [bwesterb/ftldat#2]
full log of : 
Calebs-Mac:ftldat-master caleb$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 8, in <module>
    version=get_git_version(),
  File "/Users/caleb/Desktop/ftldat-master/get_git_version.py", line 90, in get_git_version
    raise ValueError("Cannot find the version number!")
ValueError: Cannot find the version number!

**Comment by bwesterb** [comment]
Did you use git or did you download a ZIP from github?

**Comment by calebjones422** [comment]
download ZIP

**Comment by todlo** [comment]
'describe' wasn't working for me, so i changed it to '--version'... like so:

$ diff get_git_version.py.old get_git_version.py
41c41
<         p = Popen(['git', 'describe', '--abbrev=%d' % abbrev],
---
>         p = Popen(['git', '--version', '--abbrev=%d' % abbrev],

and it worked! :)

**Comment by KamodaP** [comment]
There's function get_git_version() that reads file "RELEASE-VERSION", which is missing and call ```
Popen(['git', 'describe', '--abbrev=%d' % abbrev],
                  stdout=PIPE, stderr=PIPE)
```
assumes you have a git command line installed and, actually, git project cloned locally. I'd recommend to move that into a param file or global variable.

**Comment by Killbot69** [comment]
This is a terrible installation instructions
